// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir_filter_fir_filter,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.860000,HLS_SYN_LAT=285,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3087,HLS_SYN_LUT=1430,HLS_VERSION=2025_1}" *)

module fir_filter (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r_address0,
        in_r_ce0,
        in_r_q0,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] in_r_address0;
output   in_r_ce0;
input  [31:0] in_r_q0;
output  [7:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [31:0] out_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] shift_reg_0;
reg   [31:0] shift_reg_1;
reg   [31:0] shift_reg_2;
reg   [31:0] shift_reg_3;
reg   [31:0] shift_reg_4;
reg   [31:0] shift_reg_5;
reg   [31:0] shift_reg_6;
reg   [31:0] shift_reg_7;
reg   [31:0] shift_reg_8;
reg   [31:0] shift_reg_9;
reg   [31:0] shift_reg_10;
reg   [31:0] shift_reg_11;
reg   [31:0] shift_reg_12;
reg   [31:0] shift_reg_13;
reg   [31:0] shift_reg_14;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_start;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_done;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_idle;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_ready;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_0;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_0_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_1;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_1_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_2;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_2_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_3;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_3_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_4;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_4_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_5;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_5_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_6;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_6_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_7;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_7_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_8;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_8_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_9;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_9_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_10;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_10_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_11;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_11_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_12;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_12_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_13;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_13_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_14;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_14_ap_vld;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_start;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_done;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_idle;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_ready;
wire   [7:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_in_r_address0;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_in_r_ce0;
wire   [7:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_out_r_address0;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_out_r_ce0;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_out_r_we0;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_out_r_d0;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out1;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out1_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out2;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out2_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out3;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out3_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out4;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out4_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out5;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out5_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out6;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out6_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out7;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out7_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out8;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out8_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out9;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out9_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out10;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out10_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out11;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out11_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out12;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out12_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out13;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out13_ap_vld;
wire   [31:0] grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out14;
wire    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out14_ap_vld;
reg    grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 shift_reg_0 = 32'd0;
#0 shift_reg_1 = 32'd0;
#0 shift_reg_2 = 32'd0;
#0 shift_reg_3 = 32'd0;
#0 shift_reg_4 = 32'd0;
#0 shift_reg_5 = 32'd0;
#0 shift_reg_6 = 32'd0;
#0 shift_reg_7 = 32'd0;
#0 shift_reg_8 = 32'd0;
#0 shift_reg_9 = 32'd0;
#0 shift_reg_10 = 32'd0;
#0 shift_reg_11 = 32'd0;
#0 shift_reg_12 = 32'd0;
#0 shift_reg_13 = 32'd0;
#0 shift_reg_14 = 32'd0;
#0 grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_start_reg = 1'b0;
#0 grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_start_reg = 1'b0;
end

fir_filter_fir_filter_Pipeline_VITIS_LOOP_13_1 grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_start),
    .ap_done(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_done),
    .ap_idle(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_idle),
    .ap_ready(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_ready),
    .shift_reg_0(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_0),
    .shift_reg_0_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_0_ap_vld),
    .shift_reg_1(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_1),
    .shift_reg_1_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_1_ap_vld),
    .shift_reg_2(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_2),
    .shift_reg_2_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_2_ap_vld),
    .shift_reg_3(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_3),
    .shift_reg_3_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_3_ap_vld),
    .shift_reg_4(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_4),
    .shift_reg_4_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_4_ap_vld),
    .shift_reg_5(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_5),
    .shift_reg_5_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_5_ap_vld),
    .shift_reg_6(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_6),
    .shift_reg_6_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_6_ap_vld),
    .shift_reg_7(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_7),
    .shift_reg_7_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_7_ap_vld),
    .shift_reg_8(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_8),
    .shift_reg_8_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_8_ap_vld),
    .shift_reg_9(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_9),
    .shift_reg_9_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_9_ap_vld),
    .shift_reg_10(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_10),
    .shift_reg_10_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_10_ap_vld),
    .shift_reg_11(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_11),
    .shift_reg_11_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_11_ap_vld),
    .shift_reg_12(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_12),
    .shift_reg_12_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_12_ap_vld),
    .shift_reg_13(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_13),
    .shift_reg_13_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_13_ap_vld),
    .shift_reg_14(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_14),
    .shift_reg_14_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_14_ap_vld)
);

fir_filter_fir_filter_Pipeline_VITIS_LOOP_18_2 grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_start),
    .ap_done(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_done),
    .ap_idle(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_idle),
    .ap_ready(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_ready),
    .shift_reg_0_load(shift_reg_0),
    .shift_reg_1_load(shift_reg_1),
    .shift_reg_2_load(shift_reg_2),
    .shift_reg_3_load(shift_reg_3),
    .shift_reg_4_load(shift_reg_4),
    .shift_reg_5_load(shift_reg_5),
    .shift_reg_6_load(shift_reg_6),
    .shift_reg_7_load(shift_reg_7),
    .shift_reg_8_load(shift_reg_8),
    .shift_reg_9_load(shift_reg_9),
    .shift_reg_10_load(shift_reg_10),
    .shift_reg_11_load(shift_reg_11),
    .shift_reg_12_load(shift_reg_12),
    .shift_reg_13_load(shift_reg_13),
    .shift_reg_14_load(shift_reg_14),
    .in_r_address0(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_in_r_address0),
    .in_r_ce0(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_in_r_ce0),
    .in_r_q0(in_r_q0),
    .out_r_address0(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_out_r_address0),
    .out_r_ce0(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_out_r_ce0),
    .out_r_we0(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_out_r_we0),
    .out_r_d0(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_out_r_d0),
    .p_out(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out),
    .p_out_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out_ap_vld),
    .p_out1(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out1),
    .p_out1_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out1_ap_vld),
    .p_out2(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out2),
    .p_out2_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out2_ap_vld),
    .p_out3(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out3),
    .p_out3_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out3_ap_vld),
    .p_out4(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out4),
    .p_out4_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out4_ap_vld),
    .p_out5(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out5),
    .p_out5_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out5_ap_vld),
    .p_out6(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out6),
    .p_out6_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out6_ap_vld),
    .p_out7(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out7),
    .p_out7_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out7_ap_vld),
    .p_out8(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out8),
    .p_out8_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out8_ap_vld),
    .p_out9(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out9),
    .p_out9_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out9_ap_vld),
    .p_out10(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out10),
    .p_out10_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out10_ap_vld),
    .p_out11(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out11),
    .p_out11_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out11_ap_vld),
    .p_out12(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out12),
    .p_out12_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out12_ap_vld),
    .p_out13(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out13),
    .p_out13_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out13_ap_vld),
    .p_out14(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out14),
    .p_out14_ap_vld(grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out14_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_start_reg <= 1'b1;
        end else if ((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_ready == 1'b1)) begin
            grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_start_reg <= 1'b1;
        end else if ((grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_ready == 1'b1)) begin
            grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_0 <= grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out;
    end else if (((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_0 <= grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_1 <= grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out1;
    end else if (((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_1 <= grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_10 <= grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out10;
    end else if (((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_10_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_10 <= grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_10;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_11 <= grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out11;
    end else if (((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_11_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_11 <= grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_11;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_12 <= grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out12;
    end else if (((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_12_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_12 <= grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_12;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_13 <= grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out13;
    end else if (((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_13_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_13 <= grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_13;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_14 <= grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out14;
    end else if (((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_14_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_14 <= grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_14;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_2 <= grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out2;
    end else if (((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_2 <= grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_3 <= grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out3;
    end else if (((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_3 <= grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_4 <= grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out4;
    end else if (((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_4_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_4 <= grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_5 <= grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out5;
    end else if (((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_5_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_5 <= grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_5;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_6 <= grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out6;
    end else if (((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_6_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_6 <= grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_6;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_7 <= grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out7;
    end else if (((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_7_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_7 <= grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_7;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_8 <= grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out8;
    end else if (((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_8_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_8 <= grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_8;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shift_reg_9 <= grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_p_out9;
    end else if (((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_9_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_9 <= grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_shift_reg_9;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_start = grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116_ap_start_reg;

assign grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_start = grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_ap_start_reg;

assign in_r_address0 = grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_in_r_address0;

assign in_r_ce0 = grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_in_r_ce0;

assign out_r_address0 = grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_out_r_address0;

assign out_r_ce0 = grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_out_r_ce0;

assign out_r_d0 = grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_out_r_d0;

assign out_r_we0 = grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150_out_r_we0;

endmodule //fir_filter
