

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "3"],
		"CDFG" : "fir_filter",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "285", "EstimateLatencyMax" : "285",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "in_r", "Type" : "Memory", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150", "Port" : "in_r", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "out_r", "Type" : "Memory", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "3", "SubInstance" : "grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150", "Port" : "out_r", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "shift_reg_0", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116", "Port" : "shift_reg_0", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "shift_reg_1", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116", "Port" : "shift_reg_1", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "shift_reg_2", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116", "Port" : "shift_reg_2", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "shift_reg_3", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116", "Port" : "shift_reg_3", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "shift_reg_4", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116", "Port" : "shift_reg_4", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "shift_reg_5", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116", "Port" : "shift_reg_5", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "shift_reg_6", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116", "Port" : "shift_reg_6", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "shift_reg_7", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116", "Port" : "shift_reg_7", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "shift_reg_8", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116", "Port" : "shift_reg_8", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "shift_reg_9", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116", "Port" : "shift_reg_9", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "shift_reg_10", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116", "Port" : "shift_reg_10", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "shift_reg_11", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116", "Port" : "shift_reg_11", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "shift_reg_12", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116", "Port" : "shift_reg_12", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "shift_reg_13", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116", "Port" : "shift_reg_13", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "shift_reg_14", "Type" : "OVld", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "1", "SubInstance" : "grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116", "Port" : "shift_reg_14", "Inst_start_state" : "1", "Inst_end_state" : "2"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116", "Parent" : "0", "Child" : ["2"],
		"CDFG" : "fir_filter_Pipeline_VITIS_LOOP_13_1",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "18", "EstimateLatencyMax" : "18",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "shift_reg_0", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "shift_reg_1", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "shift_reg_2", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "shift_reg_3", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "shift_reg_4", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "shift_reg_5", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "shift_reg_6", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "shift_reg_7", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "shift_reg_8", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "shift_reg_9", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "shift_reg_10", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "shift_reg_11", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "shift_reg_12", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "shift_reg_13", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "shift_reg_14", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_13_1", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_fir_filter_Pipeline_VITIS_LOOP_13_1_fu_116.flow_control_loop_pipe_sequential_init_U", "Parent" : "1"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150", "Parent" : "0", "Child" : ["4", "5"],
		"CDFG" : "fir_filter_Pipeline_VITIS_LOOP_18_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "263", "EstimateLatencyMax" : "263",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "shift_reg_0_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "shift_reg_1_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "shift_reg_2_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "shift_reg_3_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "shift_reg_4_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "shift_reg_5_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "shift_reg_6_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "shift_reg_7_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "shift_reg_8_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "shift_reg_9_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "shift_reg_10_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "shift_reg_11_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "shift_reg_12_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "shift_reg_13_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "shift_reg_14_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "in_r", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "out_r", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "p_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out1", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out2", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out3", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out4", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out5", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out6", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out7", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out8", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out9", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out10", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out11", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out12", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out13", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out14", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_18_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter6", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter6", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150.mul_32s_3s_32_2_1_U16", "Parent" : "3"},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_fir_filter_Pipeline_VITIS_LOOP_18_2_fu_150.flow_control_loop_pipe_sequential_init_U", "Parent" : "3"}]}
